repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: fix-byte-order-marker
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
    -   id: mixed-line-ending
        args: [--fix=lf]
-   repo: https://github.com/crate-ci/typos
    rev: "v1.40.0"
    hooks:
    -   id: typos
